export const PRIMARY_COLOR = '#1DB19D'
export const SECONDARY_COLOR = '#2241AC'
export const TERTIARY_COLOR = '#DAE6E8'
export const TEXT_COLOR = 'black'
export const INV_TEXT_COLOR = '#EFF6F7'
export const ALERT_COLOR = '#BE2929'
export const FONT = {small: '.5em', medium: '1em', large: '1.5em'}
export const PADDING = '10px'
export const CARD_COLOR = '#A1A1A1'
export const BORDER_RADIUS = '3px';
export const ALERT_BACKGROUND = 'pink';
export const ALERT_TEXT_COLOR = 'red';
export const WARN_BACKGROUND = 'yellow';
export const WARN_TEXT_COLOR = 'orange';
export const NOTIFY_TEXT_COLOR = 'blue';
export const NOTIFY_BACKGROUND = 'lightblue';
export const PADDING2_EVEN_LARGE = '1em';
export const BOX_SHADOW_COLOR = 'rgba(0, 0, 255, .2)';